In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing 
from sklearn.pipeline import Pipeline

In [2]:
df = pd.read_csv("rainfall.csv")
df.head()

SUBDIVISION  YEAR   JAN    FEB   MAR    APR    MAY    JUN  \
0  ANDAMAN & NICOBAR ISLANDS  1901  49.2   87.1  29.2    2.3  528.8  517.5   
1  ANDAMAN & NICOBAR ISLANDS  1902   0.0  159.8  12.2    0.0  446.1  537.1   
2  ANDAMAN & NICOBAR ISLANDS  1903  12.7  144.0   0.0    1.0  235.1  479.9   
3  ANDAMAN & NICOBAR ISLANDS  1904   9.4   14.7   0.0  202.4  304.5  495.1   
4  ANDAMAN & NICOBAR ISLANDS  1905   1.3    0.0   3.3   26.9  279.5  628.7   

     JUL    AUG    SEP    OCT    NOV    DEC  ANNUAL  Jan-Feb  Mar-May  \
0  365.1  481.1  332.6  388.5  558.2   33.6  3373.2    136.3    560.3   
1  228.9  753.7  666.2  197.2  359.0  160.5  3520.7    159.8    458.3   
2  728.4  326.7  339.0  181.2  284.4  225.0  2957.4    156.7    236.1   
3  502.0  160.1  820.4  222.2  308.7   40.1  3079.6     24.1    506.9   
4  368.7  330.5  297.0  260.7   25.4  344.7  2566.7      1.3    309.7   

   Jun-Sep  Oct-Dec  
0   1696.3    980.3  
1   2185.9    716.7  
2   1874.0    690.6  
3   1977.6    571.0  
4   1624.9    630.8

In [3]:
df.head(0)

Empty DataFrame
Columns: [SUBDIVISION, YEAR, JAN, FEB, MAR, APR, MAY, JUN, JUL, AUG, SEP, OCT, NOV, DEC, ANNUAL, Jan-Feb, Mar-May, Jun-Sep, Oct-Dec]
Index: []

# Data Preparation for Predictions

In [4]:
features = []
for element in df.head(0):
    features.append(element)
features.remove('ANNUAL')
features.remove('JAN')
features.remove('FEB')
features.remove('MAR')
features.remove('APR')
features.remove('OCT')
features.remove('NOV')
features.remove('DEC')
features.remove('AUG')
features.remove('SEP')
features.remove('Jan-Feb')
features.remove('Mar-May')
features.remove('Jun-Sep')
features.remove('Oct-Dec')
print(features)

['SUBDIVISION', 'YEAR', 'MAY', 'JUN', 'JUL']


In [5]:
#Changing SUBDIVISION to unique numbers
df.SUBDIVISION.unique()
dictionary = {}
for c, value in enumerate(df.SUBDIVISION.unique(), 1):
#     print(c, value)
    dictionary[value] = c
print(dictionary)
df["SUBDIVISION"] = df.SUBDIVISION.map(dictionary)
df.head()

{'ANDAMAN & NICOBAR ISLANDS': 1, 'ARUNACHAL PRADESH': 2, 'ASSAM & MEGHALAYA': 3, 'NAGA MANI MIZO TRIPURA': 4, 'SUB HIMALAYAN WEST BENGAL & SIKKIM': 5, 'GANGETIC WEST BENGAL': 6, 'ORISSA': 7, 'JHARKHAND': 8, 'BIHAR': 9, 'EAST UTTAR PRADESH': 10, 'WEST UTTAR PRADESH': 11, 'UTTARAKHAND': 12, 'HARYANA DELHI & CHANDIGARH': 13, 'PUNJAB': 14, 'HIMACHAL PRADESH': 15, 'JAMMU & KASHMIR': 16, 'WEST RAJASTHAN': 17, 'EAST RAJASTHAN': 18, 'WEST MADHYA PRADESH': 19, 'EAST MADHYA PRADESH': 20, 'GUJARAT REGION': 21, 'SAURASHTRA & KUTCH': 22, 'KONKAN & GOA': 23, 'MADHYA MAHARASHTRA': 24, 'MATATHWADA': 25, 'VIDARBHA': 26, 'CHHATTISGARH': 27, 'COASTAL ANDHRA PRADESH': 28, 'TELANGANA': 29, 'RAYALSEEMA': 30, 'TAMIL NADU': 31, 'COASTAL KARNATAKA': 32, 'NORTH INTERIOR KARNATAKA': 33, 'SOUTH INTERIOR KARNATAKA': 34, 'KERALA': 35, 'LAKSHADWEEP': 36}


SUBDIVISION  YEAR   JAN    FEB   MAR    APR    MAY    JUN    JUL    AUG  \
0            1  1901  49.2   87.1  29.2    2.3  528.8  517.5  365.1  481.1   
1            1  1902   0.0  159.8  12.2    0.0  446.1  537.1  228.9  753.7   
2            1  1903  12.7  144.0   0.0    1.0  235.1  479.9  728.4  326.7   
3            1  1904   9.4   14.7   0.0  202.4  304.5  495.1  502.0  160.1   
4            1  1905   1.3    0.0   3.3   26.9  279.5  628.7  368.7  330.5   

     SEP    OCT    NOV    DEC  ANNUAL  Jan-Feb  Mar-May  Jun-Sep  Oct-Dec  
0  332.6  388.5  558.2   33.6  3373.2    136.3    560.3   1696.3    980.3  
1  666.2  197.2  359.0  160.5  3520.7    159.8    458.3   2185.9    716.7  
2  339.0  181.2  284.4  225.0  2957.4    156.7    236.1   1874.0    690.6  
3  820.4  222.2  308.7   40.1  3079.6     24.1    506.9   1977.6    571.0  
4  297.0  260.7   25.4  344.7  2566.7      1.3    309.7   1624.9    630.8

# Handling the NA values

In [6]:
df.shape

(4116, 19)

In [7]:
df.isna().sum()

SUBDIVISION     0
YEAR            0
JAN             4
FEB             3
MAR             6
APR             4
MAY             3
JUN             5
JUL             7
AUG             4
SEP             6
OCT             7
NOV            11
DEC            10
ANNUAL         26
Jan-Feb         6
Mar-May         9
Jun-Sep        10
Oct-Dec        13
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
features_1 = ['AUG']

In [10]:
# Separating out the features
x  = df.loc[:, features].values
# Separating out the target
y = df.loc[:,features_1].values

# Split the data into training set and test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

# Dimensionality Reduction
Dimensionality reduction, or dimension reduction, is the transformation of data from a high-dimensional space into a low-dimensional space so that the low-dimensional representation retains some meaningful properties of the original data, ideally close to its intrinsic dimension.

In [12]:
from sklearn.decomposition import PCA 
pca = PCA(n_components=4)
pca.fit(x)

PCA(copy=True, iterated_power='auto', n_components=4, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [13]:
print(pca.explained_variance_ratio_)

[0.79961129 0.13708166 0.05500135 0.00766329]


In [14]:
pca.score(x,y)

-28.109682057097007

In the PCA analysis negative values of loadings of variable in the components of the PCA means the existence of an inverse correlation between the factor PCA and the variables.

In [15]:
pca.score_samples(x)

array([-34.59383444, -33.35279304, -29.40501404, ..., -29.68343251,
       -29.40966052, -29.27052782])

# Model 1 - Support Vector Machine (SVM)

In [16]:
from sklearn import svm
from sklearn.datasets import make_classification
clf = svm.SVR()
#X_train, y_train = make_classification()
#X_test, y_test = make_classification()
clf.fit(X_train, y_train)

D:\anaconda\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [17]:
print(clf.intercept_)

[305.74782415]


In [18]:
y_pred = clf.predict(X_test)
print(y_pred)
print(y_test)

[255.6230235  250.97775992 232.06341112 ... 203.50759715 339.26617698
 396.22460212]
[[317.4]
 [203.5]
 [ 95.5]
 ...
 [ 91.5]
 [479. ]
 [860.4]]


In [19]:
clf.score(X_test, y_test, sample_weight=None)

0.34280429793481726

In [20]:
from sklearn import metrics
mae = metrics.mean_absolute_error(y_test,y_pred)
mse = metrics.mean_squared_error(y_test,y_pred)
print(mae,mse)

109.85604996109512 23083.990469639375


In [31]:
#flood prone subdivisions
c=0
for i in y_pred:
    if i>500:
        print(i,X_test[c,0])
    c+=1

512.1336967611774 23.0
512.4125097774979 2.0
608.0000545182559 32.0
680.5064465552891 2.0
536.3288622561134 3.0
736.9385127594816 23.0
685.3614477110276 32.0
603.8963407495901 23.0
679.975339928522 2.0
638.654227124931 23.0
626.4275091910785 32.0
689.0830131606632 23.0
568.6321898981539 32.0
517.1438692163515 23.0
760.7390155270068 23.0
831.9779485515645 32.0
553.1421533538883 23.0
564.9296003223704 32.0
816.4937245359757 32.0
626.2111113382957 32.0
743.5278388170223 23.0
547.9843422626872 23.0
833.7269743798876 32.0
597.2978004865945 32.0
647.0622177597327 2.0
756.1864272074962 23.0
580.8712294491602 2.0
852.3845941951857 32.0
698.3418110202424 23.0
838.2682323642105 32.0
510.8346995132287 35.0
681.3255608446325 23.0
1087.1015094554282 2.0
811.964305721097 32.0
541.8507709189993 4.0
511.57364174380467 1.0
532.8355847662287 2.0
672.4671767478937 32.0
802.9301069188328 32.0
783.195919140372 32.0
501.27558357656267 5.0
705.029720324262 2.0
663.1434824677184 32.0
502.5978122369496 3.0
719

# Model 2 - Random Forest

In [22]:
from sklearn.ensemble import RandomForestRegressor
clf = RandomForestRegressor(max_depth=2, random_state=0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
clf.score(X_test, y_test)
print(type(y_pred))

D:\anaconda\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


<class 'numpy.ndarray'>


In [23]:
from sklearn import metrics
mae = metrics.mean_absolute_error(y_test,y_pred)
mse = metrics.mean_squared_error(y_test,y_pred)
print(mae,mse)

96.58520467449426 17044.829332702015


In [24]:
#flood prone subdivisions
c=0
for i in y_pred:
    if i>500:
        print(i,X_test[c,0])
    c+=1

574.7740915293599 32.0
648.9584794183123 2.0
606.5997891709662 3.0
665.1510362681556 23.0
665.1510362681556 32.0
646.3271640914647 35.0
652.3094583272741 2.0
608.4962489593531 23.0
665.1510362681556 32.0
665.1510362681556 23.0
652.3094583272741 32.0
600.668979899362 23.0
665.1510362681556 23.0
665.1510362681556 32.0
652.3094583272741 32.0
652.3094583272741 32.0
652.3094583272741 32.0
665.1510362681556 23.0
604.0199588083238 23.0
654.3091985390842 32.0
652.3094583272741 2.0
665.1510362681556 23.0
591.1783808674423 2.0
665.1510362681556 32.0
665.1510362681556 23.0
665.1510362681556 32.0
609.1384638979713 35.0
652.3094583272741 2.0
665.1510362681556 32.0
665.1510362681556 32.0
665.1510362681556 32.0
665.1510362681556 32.0
652.3094583272741 2.0
652.3094583272741 32.0
652.3094583272741 32.0
665.1510362681556 23.0
645.21135140973 35.0
652.3094583272741 2.0
652.3094583272741 32.0
600.5918235969272 35.0
652.3094583272741 5.0
665.1510362681556 32.0
626.382839027965 5.0
665.1510362681556 32.0
65

# Model 3 - MultiLinear Regression

In [25]:
from sklearn.linear_model import LinearRegression
clf = LinearRegression()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
clf.score(X_test, y_test)

0.5509557836699082

In [26]:
from sklearn import metrics
mae = metrics.mean_absolute_error(y_test,y_pred)
mse = metrics.mean_squared_error(y_test,y_pred)
print(mae,mse)

91.40146397442292 15772.672246086018


In [27]:
#flood prone subdivisions
c=0
for i in y_pred:
    if i>500:
        print(i,X_test[c,0])
    c+=1

[514.78864492] 23.0
[534.92952423] 2.0
[574.64204223] 32.0
[654.29832329] 2.0
[527.67234944] 3.0
[668.03290066] 23.0
[659.82298067] 32.0
[532.0802617] 23.0
[627.24129813] 2.0
[516.22726826] 5.0
[641.58100598] 23.0
[573.81342959] 32.0
[650.908223] 23.0
[621.26493461] 32.0
[685.88967844] 23.0
[785.69443093] 32.0
[620.14868141] 32.0
[883.78338939] 32.0
[503.69977777] 5.0
[672.58819362] 32.0
[725.52210986] 23.0
[512.21993166] 23.0
[772.17590887] 32.0
[547.55020271] 32.0
[697.3030787] 2.0
[699.02892414] 23.0
[639.83111029] 2.0
[802.90037012] 32.0
[645.92854251] 23.0
[535.53765096] 5.0
[798.80288354] 32.0
[550.37082511] 35.0
[593.12764123] 23.0
[1063.86405375] 2.0
[784.11833956] 32.0
[504.65830776] 1.0
[556.25769078] 2.0
[633.92128996] 32.0
[770.03035513] 32.0
[714.24464977] 32.0
[533.14649389] 5.0
[692.15934376] 2.0
[719.74161018] 32.0
[506.6507238] 3.0
[727.50118613] 32.0
[661.0242445] 23.0
[501.59042177] 35.0
[972.75716085] 2.0
[614.62015305] 32.0
[500.66287268] 35.0
[667.14130022] 5.0
[5

# Model 4 - MLP Regressor
A multilayer perceptron (MLP) is a class of feedforward artificial neural network (ANN). ... MLP utilizes a supervised learning technique called backpropagation for training. Its multiple layers and non-linear activation distinguish MLP from a linear perceptron. It can distinguish data that is not linearly separable.

In [28]:
from sklearn.neural_network import MLPRegressor
clf = MLPRegressor(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
clf.score(X_test, y_test)

D:\anaconda\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1342: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.551376852897723

In [29]:
from sklearn import metrics
mae = metrics.mean_absolute_error(y_test,y_pred)
mse = metrics.mean_squared_error(y_test,y_pred)
print(mae,mse)

91.4226284545516 15757.882194946924


In [30]:
#flood prone subdivisions
c=0
for i in y_pred:
    if i>500:
        print(i,X_test[c,0])
    c+=1

512.1336967611774 23.0
512.4125097774979 2.0
608.0000545182559 32.0
680.5064465552891 2.0
536.3288622561134 3.0
736.9385127594816 23.0
685.3614477110276 32.0
603.8963407495901 23.0
679.975339928522 2.0
638.654227124931 23.0
626.4275091910785 32.0
689.0830131606632 23.0
568.6321898981539 32.0
517.1438692163515 23.0
760.7390155270068 23.0
831.9779485515645 32.0
553.1421533538883 23.0
564.9296003223704 32.0
816.4937245359757 32.0
626.2111113382957 32.0
743.5278388170223 23.0
547.9843422626872 23.0
833.7269743798876 32.0
597.2978004865945 32.0
647.0622177597327 2.0
756.1864272074962 23.0
580.8712294491602 2.0
852.3845941951857 32.0
698.3418110202424 23.0
838.2682323642105 32.0
510.8346995132287 35.0
681.3255608446325 23.0
1087.1015094554282 2.0
811.964305721097 32.0
541.8507709189993 4.0
511.57364174380467 1.0
532.8355847662287 2.0
672.4671767478937 32.0
802.9301069188328 32.0
783.195919140372 32.0
501.27558357656267 5.0
705.029720324262 2.0
663.1434824677184 32.0
502.5978122369496 3.0
719